development:
  adapter: sqlite3
  database: keepsakes_database_development
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: keepsakes_database_testing
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: keepsakes_database_production
  pool: 5
  timeout: 5000
