development:
  adapter: postgresql
  database: dayview_database_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: dayview_database_testing
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dayview_database_production
  pool: 5
  timeout: 5000
